version: '3.1'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.servernode
    container_name: Servernode
    ports:
      - '5000:5000'
    volumes:
     - ./server:/app
    environment:
      NODE_ENV: development
    command: npm start
    links:
      - mysql

  web:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: ClientNode
    ports:
      - '3000:3000'
    volumes:
     - ./client:/app
    environment:
      NODE_ENV: development
    command: npm start

  mysql:
    image: mysql:5.7
    container_name: mysqlrabbit
    restart: always
    command: |
      --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 'isylzjkoot'
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'isylzjkoot'
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
  phpmyadminrabbit:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadminrabbit
    restart: always
    environment:
       PMA_HOST: mysqlrabbit
       PMA_PORT: 3306
    ports:
      - "8080:80"


