version: '2'
services:

  server:
    build:
      context: .
      dockerfile: Dockerfile.servernode
    container_name: Servernode
    command: npm start
    ports:
      - '5000:5000'
    volumes:
     - ./Server:/app
    environment:
      NODE_ENV: development

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: Client
    command: npm start
    ports:
      - '3000:3000'
    volumes:
     - ./Client:/app
    environment:
      NODE_ENV: development

