version: '3.1'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.servernode
    container_name: Servernode
    ports:
      - '5000:5000'
    volumes:
     - ./server:/app
    environment:
      NODE_ENV: development
    command: npm start

  web:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: ClientNode
    ports:
      - '3000:3000'
    volumes:
     - ./client:/app
    environment:
      NODE_ENV: development
    command: npm start


