FROM node:alpine
MAINTAINER Your Name

ENV APP_HOME /app
RUN mkdir $APP_HOME
WORKDIR $APP_HOME

COPY ./server/package.json $APP_HOME/
RUN cat package.json
RUN npm install
RUN npm install -g webpack


ENV NODE_ENV=production \
# PATH=$APP_HOME/node_modules/.bin:$PATH


# ADD . $APP_HOME

# Write the bundle.js static asset file
# RUN npm run build

# Boot the server
# CMD ["npm", "start"]